Projects list UI
CarbonTrader/FrontEnd pull request #1
Opened 2022-08-03 04:58 UTC by enriquegutierrezi

# Description

Added projects list user interface with its components and design, missing bring internal collections from DB.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- Added projects list UI
- Added navbar design

# Aditional Info

# Checklist
- [ ] Tests
- [ ] Documentation

2022-08-05 00:05 UTC, monotera requested changes
Muy buen trabajo! 💯 Esta quedando muy chevere, solo te hice unos pequeños comentarios.

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/styles/ProjectList.scss
> +
Formatear los archivos.

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/components/Header.jsx
> +const Header = () => {
No combinar tickets, este deberia estar en feature/header

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/components/ProjectItem.jsx
> +			</div>
No quemar info. Esta info deberia de venir del padre utilizando las funcionalidades de props.

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/containers/Layout.jsx
> +
Puedes explicar que hace esta clase?

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/containers/ProjectList.jsx
> +			</div>
No quemar informacion, esto deberia de estar en un ciclo y el ciclo deberia de recorrer un arreglo. Por ahora puedes crear un arreglo dummy.

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/styles/Header.scss
> +
Formatear archivos.

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/styles/ProjectItem.scss
> +
Formatear.

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/styles/ProjectList.scss
> +
Formatear

2022-08-05 00:05 UTC, monotera commented on carbontrader_frontend/src/styles/vars.scss
> +
No dejar estos espacios vacios. Formatear.

2022-08-05 01:59 UTC, cristobalcastrillon approved these changes

2022-08-08 15:08 UTC, monotera approved these changes

2022-08-08 15:54 UTC, merged