Checkout UI
CarbonTrader/FrontEnd pull request #3
Opened 2022-08-04 03:34 UTC by enriquegutierrezi

# Description

Added checkout user interface with its components and design, missing bring internal collections from DB.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- Added project UI

# Aditional Info

# Checklist
- [ ] Tests
- [ ] Documentation

2022-08-05 00:31 UTC, monotera requested changes
`Module not found: Error: Can't resolve 'react-router-dom'`

Me esta saliendo este error. El path de este componente lo cambiaste? Si es asi podrias especificar el path en el PR.

2022-08-05 01:58 UTC, cristobalcastrillon approved these changes

2022-08-08 15:17 UTC, monotera requested changes
Las pantallas te estan quedando muy cheveres  💯 Solo un pequeño comentario. siento que cuando se selecciona una cantidad deberia de quedarse encendido, asi se mejoraria la parte UX. Tambien el precio deberia de irse actualizando en tiempo real.

2022-08-08 15:17 UTC, monotera commented on carbontrader_frontend/src/routes/App.jsx
> +</BrowserRouter>
Cuidado con los fromatos, los archivos estan quedando desorganizados

2022-08-08 16:59 UTC, merged