Login UI
CarbonTrader/FrontEnd pull request #5
Opened 2022-08-08 04:21 UTC by enriquegutierrezi

# Description

Added Login user interface with its components and design, missing bring internal collections from DB.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- Added Login UI

# Aditional Info

# Checklist
- [ ] Tests
- [ ] Documentation

2022-08-08 15:25 UTC, monotera requested changes
Los elementos estan quedando por fuera de la pantalla. El fondo me parece muy plano, no has pensado en crear un gradiante de verdes para el fondo?

2022-08-08 18:40 UTC, cristobalcastrillon requested changes

2022-08-08 18:40 UTC, cristobalcastrillon commented on carbontrader_frontend/src/pages/Login.jsx
> +                    <input placeholder="Ingresa tu contraseña"/>
Cambiar "Ingresa tu contraseña" por "Ingresa tu nombre"

2022-08-08 18:40 UTC, cristobalcastrillon commented on carbontrader_frontend/src/components/Name.jsx
> +            <p className="firstPart">carbon</p><p className="secondPart">trader</p>
Yo le pondría un className más específico, como "titleFirstPart" o algo así.

2022-08-08 18:41 UTC, cristobalcastrillon commented on carbontrader_frontend/src/pages/Login.jsx
> +                    <input placeholder="Ingresa tu contraseña"/>
Tener en cuenta que solo debería poderse ingresar caracteres alfabéticos y no numéricos o símbolos.

2022-08-16 23:08 UTC, monotera approved these changes
Nice Job! Do you think it would be a good idea to make the borders round?

2022-08-17 00:59 UTC, cristobalcastrillon commented on carbontrader_frontend/src/components/Name.jsx
> +            <p className="title-firstPart">carbon</p><p className="title-secondPart">trader</p>
Estilizar el texto como "CarbonTrader" (en vez de "carbontrader").

2022-08-17 00:59 UTC, cristobalcastrillon commented on carbontrader_frontend/src/pages/Login.jsx
> +                            <input id="userInput" type="text" placeholder="Ingrese su usuario" />
Estamos guardando correo para el usuario, no existe username en el modelo.

2022-08-17 23:02 UTC, merged